################################################################################
# ==> Tasks for install Oracle Fussion Middleware Infrastructure software
# ==> to a RHEL 7 system. Supports version 12.1.3
# ==> author: Christos Vezalis
################################################################################

# ==> Install Fussion Middleware Infrastructure

---
- name: Downloading weblogic binary
  uri:
    url: "{{ weblogic_repo_root }}/{{ weblogic_base_path }}/{{ mw_installer }}"
    method: GET
    dest: "/tmp"
    headers:
      Accept: application/json
    validate_certs: false
    status_code: [200,304]
  delegate_to: localhost
  become: false

- name: Copy the installation binary to remote node from ansible master node
  copy:
    src: "/tmp/{{ mw_installer }}"
    dest: "/tmp/{{ mw_installer }}"

- name: creteing swap space on ec2 instance
  command: dd if=/dev/zero of={{ swap_file_path }} bs={{ swap_bs_size_mb }} count={{ swap_file_size_mb }}
           creates="{{ swap_file_path }}"


- name: Change swap file permissions
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600

#sudo chmod 600 /swapfile

- name: "Check swap file type"
  command: file {{ swap_file_path }}

- name: Make swap file
  command: " mkswap {{ swap_file_path }}"

#condition check that swap is already mounted

#sudo mkswap /swapfile

- name: Make swapon file
  command: " swapon {{ swap_file_path }} "
  

#sudo swapon /swapfile

- name: Turn on swap
  command: swapon -a

#swapon -a making all available & Devices that are already being used as swap are silently skipped.
 
- name: Verify that the procedure was successful
  command: swapon -s
  
# sudo swapon -s ( s summary) 

- name: Write swap entry in fstab
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=defaults
         passno=0
         dump=0
         state=present
  
#/swapfile swap swap defaults 0 0

#
- name: Create installer directory
  file: state=directory path={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}
- name: Copy Middleware Installer
  copy: src=/tmp/{{ mw_installer }} dest={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}
- name: Copy file for silent installation
  template: src=silent-weblogic.txt dest={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}
- name: Copy OraInst.loc
  template: src=oraInst.loc dest={{ mw_installer_folder }} owner={{ oracle_user }} group={{ oracle_group }}
- name: execute Weblogic installer
  command: "{{ jdk_folder }}/bin/java -Xms1024m -Xmx1024m -jar {{ mw_installer_folder }}/{{ mw_installer }} -silent -responseFile {{ mw_installer_folder }}/silent-weblogic.txt -invPtrLoc {{ mw_installer_folder }}/oraInst.loc"
  become: true
  become_user: '{{ oracle_user }}'
  #sudo_user: '{{ oracle_user }}'

- name: deleting the JDK-tar file after the installation complets 
  file:
    path: "/tmp/jdk-7u80-linux-x64.tar.gz"
    state: absent
  become: false  
  delegate_to: localhost

- name: deleting the Jar file after the installation complets 
  file:
    path: "/tmp/fmw_12.1.3.0.0_wls.jar" 
    state: absent
  become: false  
  delegate_to: localhost
